### PR TITLE
Fix #254 - Remove async from showMenu()

### LINKED ISSUE #254: Addition for async causes CSP errors
Our application has Content Security Policies that doesn't allow dynamically defining functions.

Recently added `async` modifier to the `showMenu` function causes the inclussion of the [regenerator](https://github.com/facebook/regenerator) polyfill by rollup. In this package there is a function that is [dynamic](https://github.com/facebook/regenerator/blob/master/packages/regenerator-runtime/runtime.js#L725)

### PR DESCRIPTION
**Pull request by Blastius**
Removes `Function("r", "regeneratorRuntime = r")(runtime);`

Check https://www.diffchecker.com/UJc10qT1#left-6 to see what the changes are to `bundle-esm.js`

Local tests all seem to work with this change.

### CODE REVIEW

**Comment by iliyaZelenko** [comment]
So much extra code in bundle and so many problems because of such a trifle in the code that was not needed at all 😄. 

Sorry for the inconvenience and thanks for the fix!

**Comment by iliyaZelenko** [comment]
I wonder why you need `"prepare": "yarn build"`? How does this help?

**Comment by Blastius** [comment]
This was an accident, we used a fork inbetween and this was the only way we could get dist files. I forgot this PR was still running and didn't create another branch :/ If you would be so kind to remove that line :)

**Pull request merged**
