### PR TITLE
feat: move items limit to props

### PR DESCRIPTION
**Pull request by samfeder**
Allow users to set their own items limit in the case they'd like to show more or less

### CODE REVIEW

**Comment by iliyaZelenko** [comment]
Thank you, I just wanted to do it soon.

**Comment by samfeder** [comment]
Glad to hear it. Love the project!

**Comment by iliyaZelenko** [comment]
But I changed prop name to `scrollItemsLimit` and also adedd `scrollItemsLimitAddAfterScroll` prop. You can check [docs](https://iliyazelenko.github.io/vue-cool-select/#/docs). 

Also i fixed bug with items limit (always maximum 20 items in menu).

**Pull request merged**
