### PR TITLE
Add menu wrapper

### PR DESCRIPTION
**Pull request by mariosh346**
Fix with purpose: add items and before items be visible all the time when scrolling

### CODE REVIEW

**Comment by iliyaZelenko** [comment]
Thank you for helping the project, but your PR has an extra file  (`package-lock.json`) and I have an idea how to do it differently. But I understood what you need, today I will release a new version for you.

I writed [CONTRIBUTING.md](https://github.com/iliyaZelenko/vue-cool-select/blob/master/CONTRIBUTING.md) for you and others contributors.

**Comment by mariosh346** [comment]
Thank you very much. The package.lock was not from my commit.

Στις Πέμ, 28 Φεβ 2019, 17:37 ο χρήστης Илья <notifications@github.com>
έγραψε:

**Comment by iliyaZelenko** [comment]
Avaliable in `2.2.1`.

All new slots:

- before-items
- after-items
- before-items-fixed
- after-items-fixed
- before-items-fixed-absolute
- after-items-fixed-absolute

I hope at least one will suit you 😄.

You can check demo [here](https://codesandbox.io/s/4zlkjr9xow?fontsize=14&initialpath=%2Fbefore-after-slots).

**Comment by mariosh346** [comment]
I believe that when there is not items these slots should be hidden

Στις Παρ, 1 Μαρ 2019 στις 2:50 π.μ., ο/η Илья <notifications@github.com>
έγραψε:

**Comment by iliyaZelenko** [comment]
@mariosh346 Some people may not like this behavior and will not be able to change it, nothing prevents you from hiding your content manually.

**Comment by iliyaZelenko** [comment]
I just released a new version `2.3.0`.

It added a convenient way to get the current displayed items through a new event `change-displayed-items`. 

I wrote a [code example](https://github.com/iliyaZelenko/vue-cool-select/blob/master/gh-pages-src/pages/dev/Example4.vue#L18) that hides slots if there are no elements.

I hope everything suits you now.

**Comment by mariosh346** [comment]
Very nice I will check it out.

Στις Παρ, 1 Μαρ 2019 στις 3:02 μ.μ., ο/η Илья <notifications@github.com>
έγραψε:

**Pull request closed without merging**
